import {
  Pane,
  majorScale,
  Card,
  IconButton,
  CogIcon,
  TrashIcon,
  TickIcon,
} from "evergreen-ui";
import Head from "next/head";
import styles from "@/styles/Terminal.module.css";
import { LightWeightChart } from "@/components/lightweightcharts";
import { GetServerSideProps } from "next";
import {
  SymbolCandles,
  fetchSymbolCandles,
  CollectionNames,
} from "@/lib/mongodb";
import { useContext, useState } from "react";
import { StateContext, useGlobalState } from "@/components/context/state";
import SymbolCard from "@/components/symbolcard";
import InputGrid from "@/components/inputgrid";

interface Props {
  isConnected: boolean;
  medium?: SymbolCandles;
}

const symbol = "TSLA";

export const getServerSideProps: GetServerSideProps<Props> = async ({
  req,
  res,
}) => {
  try {
    res.setHeader(
      "Cache-Control",
      "public, s-maxage=60, stale-while-revalidate=59"
    );

    const mediumResponse = await fetchSymbolCandles(CollectionNames.medium, {
      symbol: symbol,
    });
    if (!mediumResponse) {
      throw "error in fetchTopMedium";
    }
    // todo transform data
    return {
      props: {
        isConnected: true,
        medium: mediumResponse,
      },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
};

export default function TableOne({ isConnected, medium }: Props) {
  const { state, setPartialState } = useGlobalState();
  const [pageState, setPageState] = useState({
    symbol: symbol,
    roi: 556,
    tags: ["#6sigma", "#easy", "#wide"],
    score: 656,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Pane>
          <Card
            border="0.125rem solid"
            borderColor="black"
            background="tint1"
            padding={majorScale(2)}
            className={styles.max}
          >
            <SymbolCard {...pageState}></SymbolCard>
          </Card>
          <Pane paddingY={2}></Pane>
          <Card
            border="0.125rem solid"
            borderColor="black"
            background="tint1"
            padding={majorScale(1)}
            marginX="auto"
            alignItems="center"
          >
            {medium && (
              <LightWeightChart candlesData={medium.candles}></LightWeightChart>
            )}
          </Card>
          <Pane paddingY={2}></Pane>
          <Pane display="flex" alignItems="center">
            <IconButton icon={CogIcon} marginRight={majorScale(2)} />
            <IconButton
              icon={TrashIcon}
              intent="danger"
              marginRight={majorScale(2)}
            />
            <IconButton icon={TickIcon} intent="success" />
          </Pane>
          <Pane paddingY={2}></Pane>
          <Pane>
            <InputGrid></InputGrid>
          </Pane>
        </Pane>
      </main>
    </>
  );
}

/**
 * Example: groupIntoN([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3) => [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]
 * @param array
 * @param n
 * @returns
 */
function groupIntoN<T>(array: T[], n: number) {
  const result = [];

  for (let i = 0; i < array.length; i += 5) {
    result.push(array.slice(i, i + n));
  }

  return result;
}
